version: "3"

services:
  postgres:
    image: postgres:9.5
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/1-database.sql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/3-data.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  cachet:
    image: cachet:2.3
    ports:
      - 80:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - APP_KEY=base64:qFARZ0BKHMIkxXov19zQvdUv+5Dyx1N7hHFl5EnXwJo=
      - APP_LOG=errorlog
      - DEBUG=false
    depends_on:
      - postgres
    restart: on-failure

  cachet-monitor:
    image: cachet-monitor:0.1
    ports:
      - 8080:80
      - 8443:443
    links:
      - cachet:cachet
    depends_on:
      - cachet
    restart: on-failure
